config/routes.rb
Stm::Application.routes.draw do
  resources :stories
  resources :users
  resources :sessions

  get "logout" => "sessions#destroy", :as => "log_out"
  get "login" => "sessions#new", :as => "log_in"
  get "signup" => "users#new", :as => "sign_up"

  root :to => 'users#new'

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  belongs_to :responsible_user, :class_name => "User"

  attr_accessible :title, :body, :responsible_user, :state

  validates :title, :presence => true,
                    :length   => { :maximum => 256 }    
  validates :body, :presence => true  

  state_machine :state, :initial => :new do
    
    event :start do
      transition :new => :started
    end
  
    event :finish do
      transition :started => :finished
    end

    event :accept do
      transition :finished => :accepted
    end

    event :reject do
      transition :finished => :rejected
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories, :dependent => :destroy
  has_many :tasks, :class_name => "Story",
                   :dependent => :nullify,
                   :foreign_key => "responsible_user_id"

  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to log_in_url # прерывает цикл запроса
    end
  end
 
  def logged_in?
    !!current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
#    if @current_user
      @story = Story.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @story }
      end
#    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    valid_params = params[:story]
    responsible_user_id = params[:story][:responsible_user_id]
    valid_params.delete(:responsible_user_id)
    valid_params[:responsible_user] = User.find(responsible_user_id) unless responsible_user_id.empty?

    @story = @current_user.stories.new(valid_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, :notice => 'Story was successfully created.' }
        format.json { render :json => @story, :status => :created, :location => @story }
      else
        format.html { render :action => "new" }
        format.json { render :json => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    valid_params = params[:story]
    responsible_user_id = params[:story][:responsible_user_id]
    valid_params.delete(:responsible_user_id)
    valid_params[:responsible_user] = User.find(responsible_user_id) unless responsible_user_id.empty?
    valid_params.delete(:state) if valid_params[:state].empty?

    respond_to do |format|
      if @story.update_attributes(valid_params)
        format.html { redirect_to @story, :notice => 'Story was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simply task manager</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>


    <style type="text/css">
      body {
        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
      }
    </style>

  </head>
  <body class="<%= params[:controller] %>">

    <!-- Topbar
	 ================================================== -->
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">Simply task manager</a>
          <ul class="nav">
	    <% if current_user %>
	    <li><%= link_to "Stories", stories_path %><li>
	    <li><p>Logged in as <%= current_user.email %></p></li>
	    <li><%= link_to "Log out", log_out_path %></li>
	    <% else %>
	    <li><%= link_to "Sign up", sign_up_path %></li>
	    <li><%= link_to "Log in", log_in_path %></li>
	    <% end %>
          </ul>
        </div>
      </div>
    </div>
  

    <div class="container">

	<div class="row">
	  <div class="span16">
	    <% flash.each do |name, msg| %>
	    <div class="alert-message info" data-alert="alert">
	      <a class="close" href="#">&times;</a>
   	      <%= content_tag :p, msg %>
	    </div>
	    <% end %>
	  </div>
	</div>



      <%= yield %>
    </div>
</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :responsible_user_id %><br />
    <%= f.select "responsible_user_id", User.all.collect {|p| [ p.name, p.id ] }, :include_blank => 'None' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/_new_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :responsible_user_id %><br />
    <%= f.select "responsible_user_id", User.all.collect {|p| [ p.name, p.id ] }, :include_blank => 'None' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>User</th>
    <th>Responsible user</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.title %></td>
    <td><%= story.body %></td>
    <td><%= story.user.name %></td>
    <td><%= story.responsible_user.name if story.responsible_user %></td>
    <td><%= story.state %></td>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'new_form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @story.title %>
</p>

<p>
  <b>Body:</b>
  <%= @story.body %>
</p>

<p>
  <b>User:</b>
  <%= @story.user_id %>
</p>

<p>
  <b>Responsible user:</b>
  <%= @story.responsible_user_id %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="span16">
      <div class="clearfix">
	<%= f.label :name %><br />
	<div class="input">
	  <%= f.text_field :name %>
	</div>
      </div>
      <div class="clearfix">
	<%= f.label :email %><br />
	<div class="input">
	  <%= f.text_field :email %>
	</div>
      </div>
      <div class="clearfix">
	<%= f.label :password %><br />
	<div class="input">
	  <%= f.password_field :password %>
	</div>
      </div>
      <div class="clearfix">
	<%= f.label :password_confirmation %><br />
	<div class="input">
	  <%= f.password_field :password_confirmation %>
	</div>
      </div>

      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="content">
  <div class="page-header">
    <h1>New user</h1>
  </div>
  <div class="row">
    <div class="span16">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>